let suggestions = [
    "Fintech",
    "Dashboard",
    "Expenses",
    "Loans",
    "Bill Tracker",
    "FAQ's",
    "Profile",
    "Pending Bill",
    "Cards",
    "Graph",
    "Pay Bills",
    "View Transactions",
    "View CVV",
    "Bill details",
    "Change Theme",
    "About",
    "Download bill",
];
